### ISSUE TITLE
Duvida de django/react

### ISSUE THREAD

**Issue by Guilherme-Aguiar** [fga-gpp-mds/2018.1_Gestao_de_Internacoes_Cirurgicas_GIC#28]
Atualmente no projeto a gnt tem o app de react assim: 
![captura de tela de 2018-03-20 23-38-00](https://user-images.githubusercontent.com/23269406/37692495-d4ef7216-2c97-11e8-84e1-14fe355c7768.png)
Onde o template no django ''index.html'', se interliga com o frontend:
![captura de tela de 2018-03-20 23-39-59](https://user-images.githubusercontent.com/23269406/37692527-1283593a-2c98-11e8-9663-498bfdce68f0.png)
frontend (index.js)
![captura de tela de 2018-03-20 23-42-36](https://user-images.githubusercontent.com/23269406/37692631-ae541e30-2c98-11e8-9062-1dbb4aeecab0.png)
finalmente em (App.js) que tem o conteudo da pagina
![captura de tela de 2018-03-20 23-45-48](https://user-images.githubusercontent.com/23269406/37692669-ea4b032c-2c98-11e8-9ff6-8bd663bdfbf7.png)

Meu problema é o seguinte, eu fui tentar fazer outra pagina, configurei a views e fiz um ''teste.html'' quase igual, apenas mudando a id da div para "teste", depois criei um "test.js" nos moldes do "index.js" e por ultimo um "Testapp.js" nos moldes do "App.js" e não dá erro nenhum, apenas mostra a pagina em branco. Aparentemente essa não é a abordagem certa para criar o frontend de outra pagina, queria saber então, como eu faria outra pagina? seria um react-create-app para cada pagina?

**Comment by ulyssesBML** [comment]
Pra isso tem que ser configurado Routes no react. Vou criar uma branch com isso pq ta faltando na nossa configuração de ambiente.

**Comment by Eduardojvr** [comment]
Resolvido!
