### ISSUE TITLE
Erro no modulo rest_framework no docker 

### ISSUE THREAD

**Issue by victorhdcoelho** [fga-gpp-mds/2018.1_Gestao_de_Internacoes_Cirurgicas_GIC#51]
* ### Descrição
O docker está mandando como erro a falta do rest_framework como modulo instalado nele. O que causa confusões na hora de fazer os links entre o React e o Django.

**Comment by victorhdcoelho** [comment]
![erro_rest_framework](https://user-images.githubusercontent.com/31368363/38167115-677d5da2-3506-11e8-94ae-7271a1293e53.png)

**Comment by Eduardojvr** [comment]
Qual a versão do rest que você tá usando?

**Comment by victorhdcoelho** [comment]
djangorestframework==3.7.7

**Comment by victorhdcoelho** [comment]
Essa é a ultima atualização estável

**Comment by victorhdcoelho** [comment]
Se puder dar rebuild no docker com essa dependencia a mais seria ótimo. Ele instala pelo pip

**Comment by Eduardojvr** [comment]
https://github.com/fga-gpp-mds/2018.1_Gestao_de_Internacoes_Cirurgicas_GIC/tree/docker_configuration

**Comment by victorhdcoelho** [comment]
vlwww
